import type { LucideIcon } from "lucide-react";
import {
  Baby,
  BedDouble,
  Beer,
  Briefcase,
  Building2,
  Cake,
  Crown,
  Drama,
  Flame,
  Flower2,
  Gem,
  GraduationCap,
  Handshake,
  Heart,
  HeartHandshake,
  Landmark,
  Leaf,
  Lightbulb,
  Mic2,
  Milestone,
  Music2,
  PackageOpen,
  Palette,
  Palmtree,
  PartyPopper,
  Rocket,
  Scroll,
  Shirt,
  Sparkles,
  Star,
  Store,
  Target,
  TreePine,
  Trophy,
  Users,
  Waves,
  Zap,
} from "lucide-react";

export const iconMap = {
  target: Target,
  sparkles: Sparkles,
  handshake: Handshake,
  trophy: Trophy,
  "party-popper": PartyPopper,
  rocket: Rocket,
  building: Building2,
  briefcase: Briefcase,
  users: Users,
  drama: Drama,
  milestone: Milestone,
  store: Store,
  music: Music2,
  zap: Zap,
  lightbulb: Lightbulb,
  palmtree: Palmtree,
  flower: Flower2,
  landmark: Landmark,
  gem: Gem,
  crown: Crown,
  leaf: Leaf,
  waves: Waves,
  "bed-double": BedDouble,
  package: PackageOpen,
  cake: Cake,
  heart: Heart,
  "graduation-cap": GraduationCap,
  "tree-pine": TreePine,
  palette: Palette,
  baby: Baby,
  flame: Flame,
  scroll: Scroll,
  mic: Mic2,
  beer: Beer,
  shirt: Shirt,
  "heart-handshake": HeartHandshake,
  star: Star,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export default function Icon({ name, className }: { name: IconName; className?: string }) {
  const Component = iconMap[name];
  return <Component className={className} strokeWidth={1.75} aria-hidden />;
}
